[workspace]
members = ["crates/onboard_software", "crates/pyfrontend", "crates/simulation"]
resolver = "2"

[workspace.dependencies]
anise = "0.10.6"
hifitime = "4"
serde = { version = "1", features = ["derive"] }
rayon = "1"
nalgebra = "0.35.0"
math = { git = "https://github.com/anshgupta721/Azimuth.git", version = "0.1.0" }
dynamics = { git = "https://github.com/anshgupta721/Azimuth.git", version = "0.1.0" }
